#include <pebble.h>


/*
Helpful commands:
"export PEBBLE_PHONE=XXX.XXX.X.XXX" (e.g. export PEBBLE_PHONE=192.168.0.237) to set default pebble install destination
"pebble build" to build the watch face or app
"pebble install" to install the new watch face or app
"pebble logs" to view debug output
"pebble install --emulator basalt" to install and use in the emulator
*/

static Window *s_main_window;
static Layer *s_window_layer;

static GFont s_battery_font;
static GFont s_date_font;
static BitmapLayer *s_blade_layer;
static GBitmap *s_blade_bitmap;

static TextLayer *s_battery_layer;
static int s_battery_level;

static TextLayer *s_date_layer;
static GFont s_date_font;

static bool s_redraw_blade = true;

// Slot on-screen layout:
//     0 1
//     2 3
#define TOTAL_IMAGE_SLOTS 4
#define NUMBER_OF_IMAGES 10

// These images are 60 x 70 pixels
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0, RESOURCE_ID_IMAGE_NUM_1, RESOURCE_ID_IMAGE_NUM_2,
  RESOURCE_ID_IMAGE_NUM_3, RESOURCE_ID_IMAGE_NUM_4, RESOURCE_ID_IMAGE_NUM_5,
  RESOURCE_ID_IMAGE_NUM_6, RESOURCE_ID_IMAGE_NUM_7, RESOURCE_ID_IMAGE_NUM_8,
  RESOURCE_ID_IMAGE_NUM_9
};

// These images are 60 x 70 pixels
// black and blue with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_BLUE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0_BLUE, RESOURCE_ID_IMAGE_NUM_1_BLUE, RESOURCE_ID_IMAGE_NUM_2_BLUE,
  RESOURCE_ID_IMAGE_NUM_3_BLUE, RESOURCE_ID_IMAGE_NUM_4_BLUE, RESOURCE_ID_IMAGE_NUM_5_BLUE,
  RESOURCE_ID_IMAGE_NUM_6_BLUE, RESOURCE_ID_IMAGE_NUM_7_BLUE, RESOURCE_ID_IMAGE_NUM_8_BLUE,
  RESOURCE_ID_IMAGE_NUM_9_BLUE
};

static GBitmap *s_images[TOTAL_IMAGE_SLOTS];
static BitmapLayer *s_image_layers[TOTAL_IMAGE_SLOTS];

#define EMPTY_SLOT -1

// The state is either "empty" or the digit of the image currently in the slot.
static int s_image_slot_state[TOTAL_IMAGE_SLOTS] = {
  EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT
};

// Loads the digit image from the application's resources and
// displays it on-screen in the correct location.
// Each slot is a quarter of the screen.
static void load_digit_image_into_slot(int slot_number, int digit_value) {
  GRect bounds = layer_get_bounds(window_get_root_layer(s_main_window));
  GRect tile_bounds = gbitmap_get_bounds(s_images[slot_number]);

  s_image_slot_state[slot_number] = digit_value;

if(slot_number < 2)
{
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);
}
else
{
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_BLUE_IDS[digit_value]);
}

int x_offset = 0;
int y_offset = 0;
switch(slot_number)
{
  case 0:
  //first hour digit doesn't need offset
  break;
  case 1:
  //second hour digit only needs an X offset
    x_offset = tile_bounds.size.w;
  break;
  case 2:
    x_offset = bounds.size.w - tile_bounds.size.w*2;
    y_offset = bounds.size.h - tile_bounds.size.h;
  break;
  case 3:
     x_offset = bounds.size.w - tile_bounds.size.w;
    y_offset = bounds.size.h - tile_bounds.size.h;
  break;
}
  
  BitmapLayer *bitmap_layer = bitmap_layer_create(
    GRect(x_offset,
      y_offset,
      tile_bounds.size.w, tile_bounds.size.h));
  s_image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[slot_number]);

  //Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(s_window_layer, bitmap_layer_get_layer(bitmap_layer));
}

static void unload_digit_image_from_slot(int slot_number) {
  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    layer_remove_from_parent(bitmap_layer_get_layer(s_image_layers[slot_number]));
    bitmap_layer_destroy(s_image_layers[slot_number]);
    gbitmap_destroy(s_images[slot_number]);

    // This is now an empty slot
    s_image_slot_state[slot_number] = EMPTY_SLOT;
  }
}

static void display_value(unsigned short value, unsigned short row_number) {
  value = value % 100; // Maximum of two digits per row.

  // Column order is: | Column 0 | Column 1 |
  // (We process the columns in reverse order because that makes
  // extracting the digits from the value easier.)
  for (int column_number = 1; column_number >= 0; column_number--) {
    int slot_number = (row_number * 2) + column_number;

APP_LOG(APP_LOG_LEVEL_DEBUG, "Slot %d is %d and will become %d", slot_number, s_image_slot_state[slot_number], value % 10);

    //if(s_image_slot_state[slot_number] != (value % 10))
    {

      APP_LOG(APP_LOG_LEVEL_DEBUG, "Updating Slot %d with %d", slot_number, value % 10);

      unload_digit_image_from_slot(slot_number);
      //load leading zero
        load_digit_image_into_slot(slot_number, value % 10);
      value = value / 10;

      if(slot_number == 1 || slot_number == 3)
      {
        APP_LOG(APP_LOG_LEVEL_DEBUG, "Redraw Blade");
        s_redraw_blade = true;
      }
    }
  }

    if(s_redraw_blade)
    {

    layer_remove_from_parent(bitmap_layer_get_layer(s_blade_layer));
    layer_add_child(s_window_layer, bitmap_layer_get_layer(s_blade_layer));
    }

}

static unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }

  // Converts "0" to "12"
  unsigned short display_hour = hour % 12;
  return display_hour ? display_hour : 12;
}

static void display_time(struct tm *tick_time) {
  display_value(get_display_hour(tick_time->tm_hour), 0);
  display_value(tick_time->tm_min, 1);
}

static void display_date(struct tm *tick_time) {
  APP_LOG(APP_LOG_LEVEL_DEBUG, "display_date start");
  // Write the current momth string and day into a buffer (XXX\nXX\0)
  static char s_buffer[7];
  strftime(s_buffer, sizeof(s_buffer), "%a\n%d", tick_time);

APP_LOG(APP_LOG_LEVEL_DEBUG, "display_date: %s", s_buffer);
  // Display this date on the TextLayer
  text_layer_set_text(s_date_layer, s_buffer);

  APP_LOG(APP_LOG_LEVEL_DEBUG, "display_date end");
}


//function to update the battery percentage display
static void update_battery_display()
{
  //100%\0 is the max value
  static char battery_text[5];
  snprintf(battery_text, sizeof(battery_text), "%d%%", s_battery_level);
  text_layer_set_text(s_battery_layer, battery_text);
}

//battery state change callback
static void battery_callback(BatteryChargeState state)
{
  s_battery_level = state.charge_percent;
  update_battery_display();
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed)
{
  display_time(tick_time);
  display_date(tick_time);
}

static void background_layer_update_proc(Layer *layer, GContext *ctx)
{
  //get the bounds of the image
  GRect bitmap_bounds = gbitmap_get_bounds(s_blade_bitmap);

  //set the compositing mode (GComOpSet is required for transparency)
  graphics_context_set_compositing_mode(ctx, GCompOpSet);

  //draw the image 
  graphics_draw_bitmap_in_rect(ctx, s_blade_bitmap, bitmap_bounds);
}

static void window_load(Window *window)
{
  // Get information about the Window
  s_window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(s_window_layer);


  // grab the custom font foreground
  s_battery_font = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_SUPER_BRIGADE_20));
  s_date_font = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_SUPER_BRIGADE_16));

// APP_LOG(APP_LOG_LEVEL_DEBUG, "Calculated Text Height: %d", text_size.h);

  // Create the Hour TextLayer in the upper left corner of the screen
  // s_hours_layer = text_layer_create(GRect(0, -15, bounds.size.w,bounds.size.h+15));

  // // Create the minutes TextLayer in the lower right corner of the screen
  // s_minutes_layer = text_layer_create(GRect(0,105, bounds.size.w,bounds.size.h));

  // Use dynamic bounds so layout works on all platforms (Basalt=144x168, Emery=200x228, etc.)
  s_battery_layer = text_layer_create(GRect(0, bounds.size.h/2 - 9, bounds.size.w, 20));
  text_layer_set_background_color(s_battery_layer, GColorClear);
  text_layer_set_text_color(s_battery_layer, GColorBlue);
  text_layer_set_text_alignment(s_battery_layer, GTextAlignmentRight);

  //Add the battery text layer to the window
  layer_add_child(window_get_root_layer(window), text_layer_get_layer(s_battery_layer));

  s_date_layer = text_layer_create(GRect(0, bounds.size.h/2 - 19, 70, 40));
  text_layer_set_background_color(s_date_layer, GColorClear);
  text_layer_set_text_color(s_date_layer, GColorWhite);
  text_layer_set_text_alignment(s_date_layer, GTextAlignmentLeft);
  //Add the date text layer to the window
  layer_add_child(window_get_root_layer(window), text_layer_get_layer(s_date_layer));


// add our bitmap at the end so it can cover up the text
  //  Create GBitmap
  s_blade_bitmap = gbitmap_create_with_resource(RESOURCE_ID_IMAGE_BACKGROUND);

  // Create BitmapLayer to display the GBitmap
  s_blade_layer = bitmap_layer_create(bounds);

    // Set the bitmap onto the layer and add to the window
  bitmap_layer_set_bitmap(s_blade_layer, s_blade_bitmap);
  layer_add_child(s_window_layer, bitmap_layer_get_layer(s_blade_layer));

  layer_set_update_proc(bitmap_layer_get_layer(s_blade_layer), background_layer_update_proc);


time_t now = time(NULL);
  struct tm *tick_time = localtime(&now);
  display_time(tick_time);

  // register the tick_handler method with TickTimerService
  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
}

static void window_unload(Window *window)
{
  // Unload Custom Font
  fonts_unload_custom_font(s_battery_font);
  fonts_unload_custom_font(s_date_font);

  // Destroy GBitmap
  gbitmap_destroy(s_blade_bitmap);

  // Destroy BitmapLayer
  bitmap_layer_destroy(s_blade_layer);

  //destroy battery layer
  text_layer_destroy(s_battery_layer);

  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i);
  }

}

static void prv_init(void)
{
  s_main_window = window_create();

  window_set_background_color(s_main_window, GColorBlack);
  window_set_window_handlers(s_main_window, (WindowHandlers){
                                           .load = window_load,
                                           .unload = window_unload,
                                       });
  const bool animated = true;
  window_stack_push(s_main_window, animated);

  text_layer_set_font(s_battery_layer, s_battery_font);
  
  text_layer_set_font(s_date_layer, s_date_font);

  // Subscribe to battery state updates
  battery_state_service_subscribe(battery_callback);

  // Get the initial battery state
  battery_callback(battery_state_service_peek());
}

static void prv_deinit(void)
{
  window_destroy(s_main_window);
}

int main(void)
{
  prv_init();

  APP_LOG(APP_LOG_LEVEL_DEBUG, "Done initializing, pushed window: %p", s_main_window);

  app_event_loop();
  prv_deinit();
}
